[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm -e zellij"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.volume]
command = "pavucontrol"
animation = "fromBottom"
lazy = true
size = "15% 25%"
