[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm -e zellij"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.volume]
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
animation = "fromBottom"
lazy = true
size = "40% 50%"

[scratchpads.bluetooth]
command = "kitty --class bluetuith -e bluetuith"
class = "bluetuith"
animation = "fromBottom"
lazy = true
size = "40% 50%"

[scratchpads.yazi]
command = "kitty --class yazi -e yazi"
class = "yazi"
animation = ""
lazy = true
size = "75% 75%"
