# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "xhci_pci" "usbhid" "hid_generic" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ebc3bbaa-facc-4764-8cbc-93823dc45103";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ebc3bbaa-facc-4764-8cbc-93823dc45103".device = "/dev/disk/by-uuid/ebc3bbaa-facc-4764-8cbc-93823dc45103";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9A5E-B9DF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
